drop table if exists bookmarks;

create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text,
  url text,
  description text default null,
  rating integer default null
);

insert into bookmarks (title, url, description, rating)
values 
  ('Reddit', 'http://www.reddit.com', 'The front page of the internet', 5),
  ('Facebook', 'http://www.facebook.com', 'We are watching you', 2),
  ('Twitter', 'http://www.twitter.com', 'Good enough for the president, so...', 1),
  ('Instagram', 'http://www.instagram.com', 'No, you cant be an influencer when you grow up', 1),
  ('Project Gutenburg', 'http://www.projectgutenburg.org', 'Teach your parents how to use a kindle', 3),
  ('MySpace', 'http://www.myspace.com', 'Yes, it still exists, no you wont use it', 1),
  ('Amazon', 'http://www.amazon.com', 'Prime', 2),
  ('Chegg', 'http://www.chegg.com', 'I for one welcome our new overlords', 5),
  ('Google', 'http://www.google.com', 'Ok Google: Steal my privacy', 4),
  ('Planet Fitness', 'http://planetfitness.com', 'Aint no planet I ever heard of', 5);
  